# EzChestShop plugin configuration
# Before starting to config, please note that any usage of TABs in the config file may break the plugin so avoid using tabs and use space.
# If you need help/found a bug, contact me on Discord: Dead_Light#5608
shops:
  hologram:
    # holograms are all shown in the async way and they won't waste a single tick / nor they are buggy like some other plugins
    show-holograms: true
    # represents the holographic texts of chestshops. Use %item% to display the item's display name.
    # Use [item] for 1 Line to display the floating item. Use %buy% for buy price and %sell% for sell price.
    # %currency% is defined under economy.server-currency and %owner% represents the shops creator.
    holo-structure:
      - "&fBuy: &a%buy% %currency% &f| Sell: &c%sell% %currency%"
      - "&d%item%"
      - "[item]"
    holo-structure-adminshop:
      - "&fBuy: &a%buy% %currency% &f| Sell: &c%sell% %currency%"
      - "&d%item%"
      - "[item]"
    # hologram will get removed after x seconds if plugin doesn't detect any movement toward chest shop (default: 10)
    hologram-disappearance-delay: 10
    # Allows players to rotate their Holograms to be displayed on different sides of the Block.
    allow-rotation: true
    # an alternative hologram display system, which is slower but provides easier visibility of nearby shops.
    distance:
      toggled: true
      # Defines the range at which shops will render holograms (default: 10.0)
      range: 10.0
      # Set if items should be rendered first and holograms only when looking at the shop directly.
      show-items-first: true
  # Define which containers are applicable for chest shops:
  container:
    chests: true
    trapped-chests: true
    barrels: true
    shulkers: true
economy:
  # Used to replace %currency% for the language files and the 2nd hologram line.
  server-currency: $
commands:
  # Register easier to remember alias on server startup: /shop and /adminshop
  alias:
    ecs-shop: false
    ecsadmin-adminshop: false
permissions:
  # If set to true, players require the permission "ecs.shops.limit.X" where X is the maximum amount of shops a player can create.
  create-shops: false
